# Generated by Django 3.2.7 on 2021-10-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_z_make_mwh_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z_make',
            name='energy_month',
            field=models.FloatField(),
        ),
    ]
