# Generated by Django 3.2.7 on 2021-10-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_alter_z_make_energy_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='z_make',
            name='fix',
        ),
        migrations.RemoveField(
            model_name='z_make',
            name='total_varfix',
        ),
        migrations.RemoveField(
            model_name='z_make',
            name='var',
        ),
        migrations.AddField(
            model_name='z',
            name='energy_predict',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
