# Generated by Django 3.2.7 on 2021-10-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_auto_20211012_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='z',
            name='energy_predict',
        ),
    ]
