# Generated by Django 3.2.7 on 2021-10-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0006_z_cal'),
    ]

    operations = [
        migrations.AddField(
            model_name='z',
            name='after_saving',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='z',
            name='before_saving',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='z',
            name='energy_predict',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
