# Generated by Django 3.2.7 on 2021-10-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0007_auto_20211019_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z',
            name='after_saving',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='z',
            name='before_saving',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='z',
            name='energy_predict',
            field=models.FloatField(),
        ),
    ]
