# Generated by Django 3.2.7 on 2021-10-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0010_auto_20211020_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='z_cal',
            old_name='before_saving',
            new_name='after_allocate',
        ),
        migrations.RemoveField(
            model_name='z_cal',
            name='energy_predict',
        ),
        migrations.RemoveField(
            model_name='z_cal',
            name='saving',
        ),
        migrations.RemoveField(
            model_name='z_cal',
            name='tech_ratio',
        ),
        migrations.AddField(
            model_name='z_cal',
            name='month_predict',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='z_cal',
            name='total_energy_predict',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
