# Generated by Django 3.2.7 on 2021-10-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0012_auto_20211020_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zone', models.CharField(max_length=10)),
                ('month_range', models.CharField(max_length=150)),
                ('month_predict', models.CharField(max_length=150)),
                ('production', models.IntegerField()),
                ('working_day', models.IntegerField()),
                ('allocate', models.IntegerField()),
                ('saving', models.IntegerField()),
                ('energy_predict', models.FloatField()),
                ('before_saving', models.IntegerField()),
                ('after_saving', models.IntegerField()),
            ],
            options={
                'db_table': 'predict_total',
            },
        ),
        migrations.CreateModel(
            name='total_Cal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zone', models.CharField(max_length=10)),
                ('month_predict', models.CharField(max_length=150)),
                ('var', models.IntegerField()),
                ('fix', models.IntegerField()),
                ('total_varfix', models.IntegerField()),
                ('total_energy_predict', models.IntegerField()),
                ('before_saving', models.IntegerField()),
                ('after_saving', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='total_MAKE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zone', models.CharField(max_length=10)),
                ('month', models.CharField(default=None, max_length=150)),
                ('production_month', models.IntegerField()),
                ('energy_month', models.FloatField()),
                ('working_day', models.IntegerField()),
                ('tech_ratio', models.IntegerField()),
                ('MWh_day', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='z',
            old_name='after_allocate',
            new_name='before_saving',
        ),
        migrations.RenameField(
            model_name='z_cal',
            old_name='after_allocate',
            new_name='before_saving',
        ),
    ]
