# Generated by Django 3.2.7 on 2021-10-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0013_auto_20211022_0841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='total',
            new_name='predict',
        ),
        migrations.RenameModel(
            old_name='total_Cal',
            new_name='predict_Cal',
        ),
        migrations.RenameModel(
            old_name='total_MAKE',
            new_name='predict_MAKE',
        ),
        migrations.AlterModelTable(
            name='predict',
            table='predict_predict',
        ),
    ]
