# Generated by Django 3.2.7 on 2021-10-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0015_auto_20211023_2112'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='z_make',
            table='predict_z_make',
        ),
    ]
