# Generated by Django 3.2.7 on 2021-10-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0018_auto_20211025_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cal',
            name='after_saving',
        ),
        migrations.RemoveField(
            model_name='cal',
            name='before_saving',
        ),
        migrations.RemoveField(
            model_name='cal',
            name='month_predict',
        ),
        migrations.RemoveField(
            model_name='cal',
            name='total_energy_predict',
        ),
    ]
