# Generated by Django 3.2.7 on 2021-10-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0019_auto_20211026_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_report_production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zone', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('production', models.FloatField()),
                ('energy', models.FloatField()),
            ],
        ),
    ]
