# Generated by Django 3.2.7 on 2021-10-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0020_daily_report_production'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='daily_report_production',
            new_name='daily',
        ),
    ]
