# Generated by Django 3.2.7 on 2021-10-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0021_rename_daily_report_production_daily'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='daily',
            new_name='daily_report_production',
        ),
    ]
