# Generated by Django 3.2.7 on 2021-10-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0022_rename_daily_daily_report_production'),
    ]

    operations = [
        migrations.DeleteModel(
            name='daily_report_production',
        ),
    ]
