# Generated by Django 3.2.9 on 2021-11-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0026_predict_graph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='predict_graph',
        ),
    ]
