# Generated by Django 3.2.9 on 2021-11-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0027_delete_predict_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='name_machine',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
