# Generated by Django 3.2.9 on 2021-11-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0028_daily_name_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='name_machine',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
