# Generated by Django 3.2.9 on 2021-11-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0029_predict_name_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='predict_graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_datein', models.DateField()),
                ('graph_dateout', models.DateField()),
                ('graph_production', models.FloatField()),
                ('graph_workingday', models.FloatField()),
                ('graph_allocate', models.FloatField()),
                ('graph_saving', models.FloatField()),
                ('graph_zone', models.CharField(max_length=10)),
                ('graph_monthpredict', models.IntegerField()),
                ('graph_ts', models.DateTimeField()),
            ],
            options={
                'db_table': 'predict_graph',
            },
        ),
        migrations.RemoveField(
            model_name='predict',
            name='name_zone',
        ),
        migrations.AddField(
            model_name='predict',
            name='zone_name',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
