# Generated by Django 3.2.9 on 2021-11-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0031_auto_20211122_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Z',
        ),
        migrations.RemoveField(
            model_name='predict',
            name='after_saving',
        ),
        migrations.RemoveField(
            model_name='predict',
            name='before_saving',
        ),
        migrations.RemoveField(
            model_name='predict',
            name='energy_predict',
        ),
    ]
