# Generated by Django 3.2.9 on 2021-11-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0032_auto_20211122_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predict',
            name='month_range',
        ),
        migrations.RemoveField(
            model_name='predict',
            name='name_machine',
        ),
        migrations.AddField(
            model_name='predict',
            name='datein',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predict',
            name='dateout',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
    ]
